#!/bin/sh
set -e

for NGINX_CURRENT_PROJECT_TYPE in *
do
    TPL_CONF_FILE="/etc/nginx/conf.d/${NGINX_CURRENT_PROJECT_TYPE}.conf.tpl"
    if [[ -d "${NGINX_CURRENT_PROJECT_TYPE}" && -f "${TPL_CONF_FILE}" ]]
    then
        cd "${NGINX_CURRENT_PROJECT_TYPE}"
        for NGINX_CURRENT_SERVER_NAME in *
        do
            if [ -d "${NGINX_CURRENT_SERVER_NAME}" ]
            then
                export NGINX_CURRENT_PROJECT_TYPE
                export NGINX_CURRENT_SERVER_NAME
                export DOLLAR="$"
                envsubst < $TPL_CONF_FILE > /etc/nginx/conf.d/${NGINX_CURRENT_PROJECT_TYPE}-${NGINX_CURRENT_SERVER_NAME}.conf
            fi
        done
        cd ..
    fi
done

exec "$@"