#!/bin/sh
set -e

for NGINX_CURRENT_PROJECT_TYPE in *
do
    if [[ -d "${NGINX_CURRENT_PROJECT_TYPE}" && -f "/etc/nginx/conf.d/named-${NGINX_CURRENT_PROJECT_TYPE}.conf.tpl" ]]
    then
        cd "${NGINX_CURRENT_PROJECT_TYPE}"
        for NGINX_CURRENT_SERVER_NAME in *
        do
            if [ -d "${NGINX_CURRENT_SERVER_NAME}" ]
            then
                export NGINX_CURRENT_PROJECT_TYPE
                export NGINX_CURRENT_SERVER_NAME
                export DOLLAR="$"
                envsubst < /etc/nginx/conf.d/named-${NGINX_CURRENT_PROJECT_TYPE}.conf.tpl > /etc/nginx/conf.d/${NGINX_CURRENT_PROJECT_TYPE}-${NGINX_CURRENT_SERVER_NAME}.conf
            fi
        done
        cd ..
    fi
done

exec "$@"