version: "3.6"

services:
  app5.6:
    build:
      context: ${DOCKER_APP_CONFIG_DIR}
      args:
        PHP_VERSION: 5.6
        APP_ROOT_MULTIPLE: ${APP_ROOT_MULTIPLE}
    depends_on:
      - db
      - mailhog
    volumes:
      # PHP config files
      - ./config/app/php5.6/conf.custom.d:/usr/local/etc/php/conf.custom.d/
      - ./config/app/docker-app-multiple-entrypoint:/usr/local/bin/docker-app-multiple-entrypoint
    entrypoint:
      - docker-app-multiple-entrypoint
      - docker-php-entrypoint
    command:
      - php-fpm
    ports:
      - "${PHP_5_6_PORT}:9000"
  app7.1:
    build:
      context: ${DOCKER_APP_CONFIG_DIR}
      args:
        PHP_VERSION: 7.1
        APP_ROOT_MULTIPLE: ${APP_ROOT_MULTIPLE}
    depends_on:
      - db
      - mailhog
    volumes:
      # PHP config files
      - ./config/app/php7.1/conf.custom.d:/usr/local/etc/php/conf.custom.d/
      - ./config/app/docker-app-multiple-entrypoint:/usr/local/bin/docker-app-multiple-entrypoint
    entrypoint:
      - docker-app-multiple-entrypoint
      - docker-php-multiple-entrypoint
    command:
      - php-fpm
    ports:
      - "${PHP_7_1_PORT}:9000"
  app7.2:
    build:
      context: ${DOCKER_APP_CONFIG_DIR}
      args:
        PHP_VERSION: 7.2
        APP_ROOT_MULTIPLE: ${APP_ROOT_MULTIPLE}
    depends_on:
      - db
      - mailhog
    volumes:
      # PHP config files
      - ./config/app/php7.2/conf.custom.d:/usr/local/etc/php/conf.custom.d/
      - ./config/app/docker-app-multiple-entrypoint:/usr/local/bin/docker-app-multiple-entrypoint
    entrypoint:
      - docker-app-multiple-entrypoint
      - docker-php-entrypoint
    command:
      - php-fpm
    ports:
      - "${PHP_7_2_PORT}:9000"

  nginx:
    build:
      context: ${DOCKER_NGINX_CONFIG_DIR}
      args:
        NGINX_ROOT_MULTIPLE: ${APP_ROOT_MULTIPLE}
    depends_on:
      - app5.6
      - app7.1
      - app7.2
    volumes:
      - ./config/nginx/docker-multiple-entrypoint:/usr/local/bin/docker-nginx-entrypoint
      - ./config/nginx/conf.d/named-symfony-2.conf:/etc/nginx/conf.d/symfony-2.conf.tpl
      - ./config/nginx/conf.d/named-symfony-flex.conf:/etc/nginx/conf.d/symfony-flex.conf.tpl
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_S_PORT}:443"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
     - /var/lib/mysql
     - ${MYSQL_DUMP_DIR}:/docker-entrypoint-initdb.d:ro
    ports:
     - "${MYSQL_PORT}:3306"
   
  mailhog:
    image: mailhog/mailhog
    ports:
       - "${MAILHOG_PORT1}:1025"
       - "${MAILHOG_PORT2}:8025"
